import mod from "./generate.js";

export default mod;
export const baseTsTypeForBasePgType = mod.baseTsTypeForBasePgType;
export const createColumnDoc = mod.createColumnDoc;
export const crossSchemaTypesForAllTables = mod.crossSchemaTypesForAllTables;
export const crossSchemaTypesForSchemas = mod.crossSchemaTypesForSchemas;
export const crossTableTypesForTables = mod.crossTableTypesForTables;
export const definitionForRelationInSchema = mod.definitionForRelationInSchema;
export const domainsInSchema = mod.domainsInSchema;
export const enumDataForSchema = mod.enumDataForSchema;
export const enumTypesForEnumData = mod.enumTypesForEnumData;
export const finaliseConfig = mod.finaliseConfig;
export const generate = mod.generate;
export const generateBarrelContent = mod.generateBarrelContent;
export const generateSchemaInterface = mod.generateSchemaInterface;
export const header = mod.header;
export const indentAll = mod.indentAll;
export const moduleRoot = mod.moduleRoot;
export const quoteIfIllegalIdentifier = mod.quoteIfIllegalIdentifier;
export const relationsInSchema = mod.relationsInSchema;
export const sanitizeNamespaceIdentifier = mod.sanitizeNamespaceIdentifier;
export const schemaMappedArray = mod.schemaMappedArray;
export const schemaMappedUnion = mod.schemaMappedUnion;
export const sourceFilesForCustomTypes = mod.sourceFilesForCustomTypes;
export const tableMappedArray = mod.tableMappedArray;
export const tableMappedUnion = mod.tableMappedUnion;
export const transformCustomType = mod.transformCustomType;
export const tsForConfig = mod.tsForConfig;
export const tsTypeForPgType = mod.tsTypeForPgType;
