

export const header = () => {
  return `/*
** DON'T EDIT THIS FILE **
It's been generated by Sapatos, and is liable to be overwritten

Sapatos: https://jawj.github.io/sapatos/
Copyright (C) 2020 - 2023 George MacKerron
Released under the MIT licence: see LICENCE file
*/
`;
};
